backend:
  name: git-gateway
  branch: master
  site_domain: localhost

media_folder: static/assets
public_folder: /assets

collections:
 - name: button
   label: Button Documentation
   folder: components/0__Button/
   create: false
   extension: 'mdx'
   format: 'frontmatter'
   fields:
     - { name: path, label: Path }
     - { name: date, label: Date, widget: date }
     - { name: title, label: Title }
     - { name: body, label: Body, widget: markdown }
