backend:
  name: git-gateway
  branch: master
  site_domain: localhost

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets

collections:
 - name: components
   label: Component Documentation
   folder: components/docs
   create: false
   extension: 'mdx'
   format: 'frontmatter'
   fields:
     - { name: title, label: Title }
     - { name: body, label: Body, widget: markdown }
