backend:
  name: git-gateway
  branch: master
  site_domain: https://igloodesignsystem.netlify.app

local_backend: true

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets

collections:
 - name: Foundation
   label: Foundation
   folder: styleguide/1__Foundation
   create: false
   extension: 'mdx'
   format: 'frontmatter'
   fields:
     - { name: path, label: Path }
     - { name: date, label: Date, widget: date }
     - { name: title, label: Title }
     - { name: body, label: Body, widget: markdown }
 - name: Base Theme
   label: Base Theme
   folder: styleguide/2__Base Theme
   create: false
   extension: 'mdx'
   format: 'frontmatter'
   fields:
     - { name: path, label: Path }
     - { name: date, label: Date, widget: date }
     - { name: title, label: Title }
     - { name: body, label: Body, widget: markdown }
 - name: Components
   label: Components
   folder: components/docs
   create: false
   extension: 'mdx'
   format: 'frontmatter'
   fields:
     - { name: path, label: Path }
     - { name: date, label: Date, widget: date }
     - { name: title, label: Title }
     - { name: body, label: Body, widget: markdown }
